---

- block:
    - name: "remove docker client configuration {{ item.location }}"
      file:
        state: absent
        path: "{{ item.location }}"
  when:
    - item.enabled is defined
    - not item.enabled | default('false')

- block:
    - name: "create docker client directory"
      file:
        state: directory
        path: "{{ item.location | dirname }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: 0770

    - name: "create docker client configuration {{ item.location }}"
      template:
        src: "config.json.j2"
        dest: "{{ item.location }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: 0660
      no_log: true
  when:
    - item.enabled is defined
    - item.enabled | default('false')

...
