---

- block:
    - name: "remove docker client configuration {{ item.location }}"
      docker_client_config:
        state: absent
        dest: "{{ item.location }}"
  when:
    - item.enabled is defined
    - not item.enabled | default('false')

- block:
    - name: "create docker client directory"
      file:
        state: directory
        path: "{{ item.location | dirname }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: 0770

    - name: create client configuration {{ item.location }}
      docker_client_config:
        state: present
        dest: "{{ item.location }}"
        auths: "{{ item.auths | default({}) }}"
        formats: "{{ item.formats | default({}) }}"
      no_log: true
  when:
    - item.enabled is defined
    - item.enabled | default('false')

...
