---

- name: "remove docker client configuration {{ item.location }}"
  docker_client_config:
    state: absent
    dest: "{{ item.location }}"
  when:
    - not item.enabled | default('false') | bool

- name: client configuration
  when:
    - item.enabled | default('false') | bool
  block:
    - name: "create docker client directory"
      ansible.builtin.file:
        state: directory
        path: "{{ item.location | dirname }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: 0770

    - name: create client configuration {{ item.location }}
      docker_client_config:
        state: present
        dest: "{{ item.location }}"
        auths: "{{ item.auths | default({}) }}"
        formats: "{{ item.formats | default({}) }}"
      # no_log: true

...
