---

- name: remove default packaged docker
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
    state: absent
  when:
    - not (ansible_os_family | lower == 'archlinux' or
           ansible_os_family | lower | replace(' ', '') == 'artixlinux')

- name: install docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: "{{ docker_state }}"

- name: ensure containerd is running and enabled on archlinux
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: "{{ docker_service.enable }}"
  when:
    - ansible_os_family | lower == 'archlinux'
    - ansible_service_mgr | lower == 'systemd'

...
