---

- name: remove default packaged docker
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
    state: absent
  when:
    - not (ansible_os_family | lower == 'archlinux' or
           ansible_os_family | lower | replace(' ', '') == 'artixlinux')

- name: install docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: "{{ docker_state }}"

- name: create docker run configuration
  ansible.builtin.template:
    src: "docker.j2"
    dest: "{{ docker_defaults_directory }}/docker"
    force: true
    owner: root
    group: root
    mode: 0640
  notify:
    - reload docker

- name: ensure containerd is running and enabled on archlinux
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: "{{ docker_service.enable }}"
  when:
    - ansible_os_family | lower == 'archlinux'
    - ansible_service_mgr | lower == 'systemd'

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: wait for running docker
  ansible.builtin.wait_for:
    path: /run/docker.pid
    state: present
    msg: Timeout to find file /run/docker.pid

- name: define docker_version
  docker_version:
  register: docker_version

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/docker.fact
    mode: 0755

...
