---

docker_packages:
  - docker-ce

docker_defaults_python_packages:
  - name: docker
    version: 6.0.0
  - name: setuptools
    version: 39.1.0
  - name: requests
    version: 2.28.0

docker_defaults_compose:
  install: false
  version: 1.29.2

docker_defaults_service:
  tls:
    verify: false
    ca_cert: ""
    cert: ""
    key: ""
  storage:
    opts: []
    driver: ""
  config_file: "/etc/docker/daemon.json"

docker_defaults_tls:
  verify: false
  ca_cert: ""
  cert: ""
  key: ""

docker_defaults_config:
  authorization_plugins: []
  bip: ""
  bridge: ""
  data_root: "/var/lib/docker"
  debug: false
  default_gateway: ""
  default_gateway_v6: ""
  default_shm_size: ""
  default_ulimits: {}
  dns: []
  dns_opts: []
  dns_search: []
  experimental: false
  fixed_cidr: ""
  fixed_cidr_v6: ""
  group: ""
  hosts: []
  insecure_registries: []
  ip: ""
  ip_forward:
  ip_masq:
  iptables:
  ip6tables:
  ipv6:
  labels: []
  log_driver: ""
  log_level: ""
  log_opts: {}
  max_concurrent_downloads: 3
  max_concurrent_uploads: 5
  max_download_attempts:
  metrics_addr: ""
  oom_score_adjust:
  pidfile:
  raw_logs:
  registry_mirrors: []
  seccomp_profile: ""
  selinux_enabled: false
  shutdown_timeout:
  storage_driver: ""
  storage_opts: []
  tls:
    verify: false
    ca_cert: ""
    cert: ""
    key: ""

docker_containerd:
  socket: /run/containerd/containerd.sock

docker_defaults_directory: /etc/default

...
