---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: instance
    image: "diodonfrost/ansible-${DISTRIBUTION:-debian:10}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:Z
      # needs only by ubuntu 20.04
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2:Z

provisioner:
  name: ansible
  ansible_args:
    - --diff
  #   - -v
  config_options:
    defaults:
      deprecation_warnings: True
      stdout_callback: yaml
      # remote_tmp: /tmp/ansible-${USER}

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
