---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:

    - name: update package cache
      package:
        update_cache: true

    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

...
