---

name: code linter

on:
  schedule:
    - cron: "10 3 * * 0"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'main'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "tasks/**"
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "tasks/**"

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - name: lint
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ANSIBLE: true
          # VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true

...
